spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000